#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# SEED Emulator — Vagrant VM Manager
#
# Usage: seed_vagrant.sh <up|down|status|ssh>
#
# Creates and manages VMs from configs/cluster.yaml using Vagrant.
# Supports VirtualBox, VMware, and libvirt providers.
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CLUSTER_CONFIG="${REPO_ROOT}/configs/cluster.yaml"
VAGRANTFILE="${REPO_ROOT}/Vagrantfile"

log()  { echo "[seed_vagrant] $*"; }
warn() { echo "[seed_vagrant] WARN: $*" >&2; }
die()  { echo "[seed_vagrant] ERROR: $*" >&2; exit 1; }

# ============================================================================
# Load environment config
# Each user declares their environment in configs/env.sh (gitignored).
# See configs/env.sh.example for a template.
# ============================================================================

ENV_FILE="${SCRIPT_DIR}/../configs/env.sh"
if [[ -f "${ENV_FILE}" ]]; then
  # shellcheck source=/dev/null
  source "${ENV_FILE}"
fi

# Fail fast when running on WSL but required env is missing.
# WSL users must configure configs/env.sh to bridge to Windows hypervisors.
if grep -qi microsoft /proc/version 2>/dev/null; then
  if [[ -z "${VAGRANT_WSL_ENABLE_WINDOWS_ACCESS:-}" ]]; then
    die "Running on WSL but VAGRANT_WSL_ENABLE_WINDOWS_ACCESS is not set.
Did you copy configs/env.sh.example to configs/env.sh and edit it?
  cp configs/env.sh.example configs/env.sh
  # then uncomment the WSL section inside"
  fi
fi

usage() {
  cat <<'EOF'
Usage: seed_vagrant.sh <action> [args]

Actions:
  up          Create and start VMs
  down        Destroy all VMs
  status      Show VM status
  ssh <node>  SSH into a node (e.g., ssh master)
  generate    Only generate Vagrantfile without starting VMs

Config: configs/cluster.yaml
EOF
  exit 0
}

# ============================================================================
# Read cluster.yaml with Python
# ============================================================================

read_config() {
  python3 -c "
import yaml, json, sys

with open('${CLUSTER_CONFIG}') as f:
    cfg = yaml.safe_load(f)

# Output as JSON for easy bash parsing
json.dump(cfg, sys.stdout)
"
}

get_config_value() {
  local key="$1"
  python3 -c "
import yaml, sys

with open('${CLUSTER_CONFIG}') as f:
    cfg = yaml.safe_load(f)

keys = '${key}'.split('.')
val = cfg
for k in keys:
    if isinstance(val, dict):
        val = val.get(k, '')
    else:
        val = ''
        break
print(val if val is not None else '')
"
}

get_nodes_json() {
  python3 -c "
import yaml, json, sys

with open('${CLUSTER_CONFIG}') as f:
    cfg = yaml.safe_load(f)

json.dump(cfg.get('nodes', []), sys.stdout)
"
}

# ============================================================================
# Generate Vagrantfile from cluster.yaml
# ============================================================================

generate_vagrantfile() {
  command -v vagrant &>/dev/null || die "Vagrant not installed. Install from https://developer.hashicorp.com/vagrant/install"
  command -v python3 &>/dev/null || die "python3 not found"

  log "Generating Vagrantfile from ${CLUSTER_CONFIG}"

  [[ -f "${CLUSTER_CONFIG}" ]] || die "Config not found: ${CLUSTER_CONFIG}"

  export SCRIPTS_DIR="${SCRIPT_DIR}"
  python3 - <<'PYEOF'
import yaml
import sys
import os

# Pull in normalize_cluster() so this script accepts both shorthand and
# explicit nodes lists in cluster.yaml.
sys.path.insert(0, os.environ["SCRIPTS_DIR"])
from normalize_cluster import normalize_cluster

config_path = os.environ.get("CLUSTER_CONFIG")
with open(config_path) as f:
    raw = yaml.safe_load(f)
cfg = normalize_cluster(raw)

provider = cfg.get("provider", "virtualbox")
box = cfg.get("box", "ubuntu/jammy64")
network_type = cfg.get("network", {}).get("type", "private_network")
nested_virt = bool(cfg.get("nested_virt", False))
nodes = cfg.get("nodes", [])

vagrantfile_path = os.environ.get("VAGRANTFILE")

with open(vagrantfile_path, "w") as vf:
    vf.write('# Auto-generated by seed_vagrant.sh from configs/cluster.yaml\n')
    vf.write('# Do not edit manually — edit configs/cluster.yaml instead.\n\n')
    vf.write('Vagrant.configure("2") do |config|\n')
    vf.write(f'  config.vm.box = "{box}"\n')
    vf.write('  config.ssh.insert_key = false\n\n')

    # Allocate host SSH ports deterministically: master=2222, workers=2200,2201,…
    # Each VM gets explicit forwarded_port + n.ssh.host/port. Why all of them
    # and not just master: vmware_desktop's `vagrant ssh-config` switches *every*
    # VM's HostName to the VMnet NAT IP (192.168.150.x) once any explicit
    # forwarded_port exists in the file — the VMnet IP is unreachable from WSL,
    # so SSH from the controller times out. Pinning per-VM ssh.host/port
    # forces ssh-config to emit 127.0.0.1:<host_port> for every node.
    worker_idx = 0
    for node in nodes:
        name = node["name"]
        ip = node["ip"]
        cpus = node.get("cpus", 2)
        memory = node.get("memory", 4096)
        role = node.get("role", "worker")
        if role == "master":
            ssh_host_port = 2222
        else:
            ssh_host_port = 2200 + worker_idx
            worker_idx += 1

        vf.write(f'  config.vm.define "{name}" do |n|\n')
        vf.write(f'    n.vm.hostname = "{name}"\n')
        vf.write(f'    n.vm.network "{network_type}", ip: "{ip}"\n')
        vf.write(f'    n.vm.network "forwarded_port", guest: 22, host: {ssh_host_port}, host_ip: "127.0.0.1", id: "ssh", auto_correct: true\n')
        if role == "master":
            # Forward K3s API only on master so the controller (e.g. WSL)
            # can reach it via 127.0.0.1:16443; the cluster's private network
            # (192.168.77.x) is unreachable from WSL.
            vf.write(f'    n.vm.network "forwarded_port", guest: 6443, host: 16443, host_ip: "127.0.0.1", auto_correct: true\n')
        vf.write(f'    n.ssh.host = "127.0.0.1"\n')
        vf.write(f'    n.ssh.port = {ssh_host_port}\n')
        vf.write('\n')

        # VirtualBox provider
        vf.write(f'    n.vm.provider "virtualbox" do |vb|\n')
        vf.write(f'      vb.name = "seedemu-{name}"\n')
        vf.write(f'      vb.cpus = {cpus}\n')
        vf.write(f'      vb.memory = {memory}\n')
        vf.write(f'      # Fix /dev/null issue on Windows/WSL\n')
        vf.write(f'      vb.customize ["modifyvm", :id, "--uart1", "off"]\n')
        vf.write(f'      vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]\n')
        if nested_virt:
            vf.write(f'      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]\n')
        vf.write(f'    end\n')
        vf.write('\n')

        # VMware provider
        vf.write(f'    n.vm.provider "vmware_desktop" do |vmw|\n')
        vf.write(f'      vmw.vmx["numvcpus"] = "{cpus}"\n')
        vf.write(f'      vmw.vmx["memsize"] = "{memory}"\n')
        # Allow promiscuous mode on the private-network NIC. SEED's mini_internet
        # uses macvlan to model IX peering; cross-VM L2 traffic between
        # router pods on different K3s workers needs the host vmnet to forward
        # MACs other than the VM's own. Without this, EBGP TCP is stuck at
        # Connect and verify reports bgp_not_established.
        vf.write(f'      vmw.vmx["ethernet1.allowPromiscuous"] = "TRUE"\n')
        if nested_virt:
            vf.write(f'      vmw.vmx["vhv.enable"] = "TRUE"\n')
        vf.write(f'    end\n')
        vf.write('\n')

        # Libvirt provider
        vf.write(f'    n.vm.provider "libvirt" do |lv|\n')
        vf.write(f'      lv.cpus = {cpus}\n')
        vf.write(f'      lv.memory = {memory}\n')
        if nested_virt:
            vf.write(f'      lv.nested = true\n')
            vf.write(f'      lv.cpu_mode = "host-passthrough"\n')
        vf.write(f'    end\n')

        vf.write(f'  end\n\n')

    vf.write('end\n')

print(f"Vagrantfile generated at {vagrantfile_path}")
PYEOF

  log "Vagrantfile generated: ${VAGRANTFILE}"
}

# ============================================================================
# Actions
# ============================================================================

action_up() {
  local provider
  provider="$(get_config_value provider)"
  [[ -n "${provider}" ]] || provider="virtualbox"

  generate_vagrantfile

  log "Starting VMs with provider: ${provider}"
  cd "${REPO_ROOT}"
  vagrant up --provider="${provider}"

  # Export SSH config + fix WSL key perms FIRST. We need this for the verify
  # step below (vagrant's own `vagrant ssh` is unreliable under WSL → Windows
  # hypervisor — it sporadically fails even after `Machine booted and ready!`).
  # Using ssh -F output/vagrant_ssh_config goes through the same forwarded
  # ports vagrant set up but with a stable client.
  mkdir -p "${REPO_ROOT}/output"
  vagrant ssh-config > "${REPO_ROOT}/output/vagrant_ssh_config" 2>/dev/null || true

  # Fix SSH key permissions for WSL: copy keys to Linux filesystem
  local key_dir="/home/$(whoami)/.vagrant_keys"
  mkdir -p "${key_dir}"
  if grep -q '/mnt/c/' "${REPO_ROOT}/output/vagrant_ssh_config" 2>/dev/null; then
    grep 'IdentityFile /mnt/c/' "${REPO_ROOT}/output/vagrant_ssh_config" \
      | awk '{print $2}' | sort -u | while read -r src; do
      local fname
      fname="$(basename "${src}")"
      cp "${src}" "${key_dir}/${fname}" 2>/dev/null || true
      chmod 600 "${key_dir}/${fname}" 2>/dev/null || true
    done
    sed -i "s|IdentityFile /mnt/c/[^ ]*insecure_private_keys/|IdentityFile ${key_dir}/|g" \
      "${REPO_ROOT}/output/vagrant_ssh_config"
    log "SSH keys copied to ${key_dir} with correct permissions"
  fi

  log "SSH config exported to output/vagrant_ssh_config"

  # Append IP-based aliases so the upstream SEED scripts (which connect via
  # `ssh vagrant@192.168.77.10` and friends) get routed through the same
  # forwarded ports we use for the symbolic master/workerN names.
  # Without this, anything that runs under scripts/ssh-wrapper.sh (or
  # vanilla ssh -F vagrant_ssh_config) hitting a private cluster IP times out
  # because the controller (e.g. WSL) can't reach the VMware private network.
  python3 - "${REPO_ROOT}/output/vagrant_ssh_config" "${CLUSTER_CONFIG}" <<'PY'
import sys, yaml, re

cfg_path, cluster_path = sys.argv[1], sys.argv[2]
text = open(cfg_path).read()
# Strip any previous aliases we appended (idempotent regeneration).
text = re.sub(r"\n# >>> seed_vagrant IP aliases.*?# <<< seed_vagrant IP aliases\n", "\n", text, flags=re.DOTALL)

with open(cluster_path) as f:
    cluster = yaml.safe_load(f) or {}
nodes = [n for n in cluster.get("nodes") or [] if n.get("ip")]

def block_for(name: str) -> str:
    m = re.search(rf"(Host {re.escape(name)}\n(?:[^\n]+\n)+)", text)
    return m.group(1) if m else ""

aliases = ["\n# >>> seed_vagrant IP aliases (let upstream scripts ssh vagrant@<private-ip> via port forward)"]
for node in nodes:
    body = block_for(node["name"])
    if not body:
        continue
    aliased = body.replace(f"Host {node['name']}", f"Host {node['ip']}", 1)
    aliases.append(aliased.rstrip())
aliases.append("# <<< seed_vagrant IP aliases\n")

open(cfg_path, "w").write(text.rstrip() + "\n" + "\n".join(aliases))
PY
  log "SSH config: appended IP aliases for upstream-script compatibility"

  log "Verifying SSH connectivity..."
  local nodes
  nodes="$(python3 -c "
import yaml, sys
with open('${CLUSTER_CONFIG}') as f:
    for node in yaml.safe_load(f).get('nodes', []):
        print(node['name'])
")"

  local ssh_cfg="${REPO_ROOT}/output/vagrant_ssh_config"
  local all_ok=true
  local failed=()
  for node in ${nodes}; do
    if ssh -F "${ssh_cfg}" -o ConnectTimeout=10 -o BatchMode=yes "${node}" hostname &>/dev/null; then
      log "  ${node}: OK"
    else
      warn "  ${node}: SSH failed"
      all_ok=false
      failed+=("${node}")
    fi
  done

  if [[ "${all_ok}" == "true" ]]; then
    log "All VMs are up and SSH accessible"
  else
    # Fail-fast: downstream Ansible-based stages would otherwise look like
    # they "succeed" for unreachable nodes (changed=N, but nothing actually
    # installed), which is much harder to debug than dying here.
    die "SSH check failed for: ${failed[*]}.  Try: vagrant reload ${failed[*]}  (or destroy/up)"
  fi
}

action_down() {
  cd "${REPO_ROOT}"
  if [[ -f "${VAGRANTFILE}" ]]; then
    log "Destroying VMs..."
    vagrant destroy -f
    log "VMs destroyed"
  else
    warn "No Vagrantfile found"
  fi
}

action_status() {
  cd "${REPO_ROOT}"
  if [[ -f "${VAGRANTFILE}" ]]; then
    vagrant status
  else
    warn "No Vagrantfile found. Run 'seed_vagrant.sh up' first."
  fi
}

action_ssh() {
  local node="${1:-}"
  [[ -n "${node}" ]] || die "Usage: seed_vagrant.sh ssh <node-name>"

  cd "${REPO_ROOT}"
  vagrant ssh "${node}"
}

# ============================================================================
# Main
# ============================================================================

main() {
  local action="${1:-}"
  shift || true

  case "${action}" in
    up)       action_up ;;
    down)     action_down ;;
    status)   action_status ;;
    ssh)      action_ssh "$@" ;;
    generate) generate_vagrantfile ;;
    -h|--help|help|"") usage ;;
    *)        die "Unknown action: ${action}. Run with --help for usage." ;;
  esac
}

export CLUSTER_CONFIG VAGRANTFILE
main "$@"
