#!/usr/bin/env bash
set -euo pipefail

# macOS PATH bridge: see seed_all.sh comment.
if [ "$(uname)" = "Darwin" ]; then
  for _p in /opt/homebrew/bin /usr/local/bin; do
    [ -d "$_p" ] || continue
    case ":${PATH}:" in *":$_p:"*) ;; *) PATH="$_p:${PATH}" ;; esac
  done
  export PATH; unset _p
fi

# ============================================================================
# SEED Emulator — Top-level driver for the upstream profile runner
#
# Usage: seed_run.sh <action>
#
# Reads configs/deploy.yaml + the seed-emulator cluster inventory, exports the
# corresponding SEED_* environment variables that the upstream tooling already
# expects, and execs scripts/seed_k8s_profile_runner.sh with the resolved
# profile and the action.
#
# Examples:
#   bash scripts/seed_run.sh all       # full pipeline (compile→build→deploy→...)
#   bash scripts/seed_run.sh compile   # only compile the topology to k8s.yaml
#   bash scripts/seed_run.sh deploy    # only kubectl apply
#   bash scripts/seed_run.sh verify    # only verification
#   bash scripts/seed_run.sh observe   # only observability artifacts
#   bash scripts/seed_run.sh report    # only report generation
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"           # vagrant-deploy/
SEED_DIR="$(cd "${REPO_ROOT}/.." && pwd)"             # seed-emulator/

# PR-6: prepend our ssh/scp shim so any upstream script that runs
# `ssh vagrant@<private-cluster-ip>` is transparently routed through the
# vagrant-managed NAT port forwards (HostName/Port mapping lives in
# output/vagrant_ssh_config, including the IP-based aliases that
# seed_vagrant.sh appends). Without this, controller (e.g. WSL) → cluster
# private network is unreachable and upstream preflight times out.
export PATH="${SCRIPT_DIR}/bin:${PATH}"

# Force the upstream k3s_fetch_kubeconfig.sh (called e.g. by tier2 doctor
# stage) to write a kubeconfig whose API server points at our forwarded
# host port instead of the cluster's private IP that the controller can't
# reach. See also Vagrantfile master forwarded_port 6443→16443 and the
# tls-san=127.0.0.1 entry in the K3s server config.
export SEED_K3S_SERVER_URL_OVERRIDE="https://127.0.0.1:16443"

DEPLOY_CONFIG="${REPO_ROOT}/configs/deploy.yaml"
K3S_CONFIG="${REPO_ROOT}/configs/k3s.yaml"
CLUSTER_CONFIG="${REPO_ROOT}/configs/cluster.yaml"
ADVANCED_CONFIG="${REPO_ROOT}/configs/advanced.yaml"
TUNING_CONFIG="${REPO_ROOT}/configs/tuning.yaml"
PROFILE_RUNNER="${SEED_DIR}/scripts/seed_k8s_profile_runner.sh"
CLUSTER_INVENTORY_LOADER="${SEED_DIR}/scripts/seed_k8s_cluster_inventory.sh"

log() { echo "[seed_run] $*"; }
die() { echo "[seed_run] ERROR: $*" >&2; exit 1; }

usage() {
  cat <<'EOF'
Usage: seed_run.sh <action>

Configs read by this wrapper:
  configs/deploy.yaml                   Common knobs (profile, cni, schedule)
  configs/advanced.yaml                 Experiment / profile-specific extras
  configs/tuning.yaml                   Timeouts / retries / parallelism
  seed-emulator/configs/clusters/*.yaml Cluster description (generated by
                                        seed_k3s_setup.sh install)
  configs/provider_settings.yaml        Local hypervisor bin_dir (per-user)
  configs/proxy_settings.yaml           Local proxy (per-user, optional)

Common actions (forwarded to upstream profile runner):
  all          Full pipeline: compile → build → deploy → start → verify →
               observe → report
  compile      Run KubernetesCompiler on the topology Python script
  build        Build container images and push to the in-cluster registry
  deploy       kubectl apply the compiled manifests
  start-bird   Start BIRD on routers (separate phase)
  start-kernel Start the BIRD kernel protocol
  phase-start  Combined start-bird + start-kernel with phase coordination
  verify       Run placement / BGP / connectivity checks
  observe      Snapshot diagnostics for the run
  report       Build the final report from validation+observe artifacts
  triage       Inspect the most recent failure
  doctor       Quick environment health check
EOF
  exit 0
}

[[ $# -ge 1 ]] || usage
[[ "${1:-}" =~ ^(-h|--help|help)$ ]] && usage
ACTION="$1"

[[ -f "${DEPLOY_CONFIG}" ]] || die "Missing ${DEPLOY_CONFIG}"
[[ -x "${PROFILE_RUNNER}" ]] || die "Missing ${PROFILE_RUNNER}"
[[ -f "${CLUSTER_INVENTORY_LOADER}" ]] || die "Missing ${CLUSTER_INVENTORY_LOADER}"
command -v ansible-playbook &>/dev/null || true   # not required here, but informative
command -v python3 &>/dev/null || die "python3 not found"
command -v kubectl &>/dev/null  || die "kubectl not found (the upstream runner needs it)"

# 1) Local env (WSL detect, hypervisor bin_dir, proxy) from declarative configs
# shellcheck source=/dev/null
source "${SCRIPT_DIR}/load_provider_path.sh"

# 2) Cluster description → SEED_K3S_*, SEED_REGISTRY_*, SEED_CNI_MASTER_INTERFACE
# REPO_ROOT is consumed by the loader to resolve configs/clusters/*.yaml.
SAVED_REPO_ROOT="${REPO_ROOT:-}"
REPO_ROOT="${SEED_DIR}"
# shellcheck source=/dev/null
source "${CLUSTER_INVENTORY_LOADER}"
seed_load_cluster_inventory
REPO_ROOT="${SAVED_REPO_ROOT}"

if [[ "${SEED_CLUSTER_INVENTORY_LOADED:-false}" != "true" ]]; then
  die "Cluster inventory not loaded. Did you run seed_k3s_setup.sh install yet?"
fi

# 2.5) If the user picked profile=custom with a topology_file, register a
# 'custom' profile in the upstream profile catalog so profile_runner.sh can
# find it. Idempotent — also removes a stale custom entry when the user
# switches back to a built-in profile.
python3 "${SCRIPT_DIR}/inject_custom_profile.py" \
  --deploy "${DEPLOY_CONFIG}" \
  --k3s "${K3S_CONFIG}" \
  --profile-yaml "${SEED_DIR}/configs/seed_k8s_profiles.yaml" \
  --repo-root "${REPO_ROOT}"

# 3) Deployment knobs (common + k3s + advanced + tuning) → SEED_*
# k3s.yaml is included so SEED_CNI_TYPE comes from the same place ansible reads
# its cni_type variable — single source of truth, no drift.
deploy_exports="$(python3 "${SCRIPT_DIR}/gen_deploy_env.py" \
  --deploy   "${DEPLOY_CONFIG}" \
  --k3s      "${K3S_CONFIG}" \
  --advanced "${ADVANCED_CONFIG}" \
  --tuning   "${TUNING_CONFIG}")"
if [[ -n "${deploy_exports}" ]]; then
  eval "${deploy_exports}"
fi

PROFILE="${SEED_EXPERIMENT_PROFILE:-mini_internet}"

log "Profile : ${PROFILE}"
log "Action  : ${ACTION}"
log "Cluster : ${SEED_K3S_CLUSTER_NAME:-?} (master ${SEED_K3S_MASTER_IP:-?})"
log "Registry: ${SEED_REGISTRY:-?}"
log "Namespace: ${SEED_NAMESPACE:-(profile default)}"
log "CNI iface: ${SEED_CNI_MASTER_INTERFACE:-?}"

# 4) Custom profile bypasses.
#
# For PROFILE=custom we bypass parts of the upstream profile_runner because
# it was designed around hard-coded built-in profile names (mini_internet,
# real_topology_rr, ...) and our custom topologies don't fit. Two bypasses:
#
# (a) ACTION=compile  → invoke our run_topology.py driver, which reads our
#     yaml configs and calls the topology's run(...) with EXPLICIT KEYWORD
#     ARGUMENTS (no os.environ.get / no SEED_* env vars hidden in the data
#     flow). This matches the upstream Docker.py / examples/basic/* style
#     SEED's original author intended. Output ends up at
#     seed-emulator/output/profile_runs/custom/<run_id>/compiled/ with the
#     `latest` symlink updated, so subsequent build/deploy stages (still
#     routed through upstream profile_runner) find it the usual way.
#
# (b) ACTION=start-bird / start-kernel → invoke the topology-agnostic
#     python helpers directly, sidestepping profile_runner.sh:1340's
#     PROFILE_ID == "mini_internet" gate which would otherwise silently
#     drop into "START_BIRD_UNSUPPORTED" and leave BIRD un-launched.
#     The helpers enumerate router pods by K8s label, not profile name.
if [ "${PROFILE}" = "custom" ]; then
  # (a) compile: pure-kwargs driver, no env-var hand-off.
  if [ "${ACTION}" = "compile" ]; then
    log "custom profile bypass: invoke run_topology.py (kwargs-based, no env)"
    exec python3 "${SCRIPT_DIR}/run_topology.py" \
      --deploy   "${DEPLOY_CONFIG}" \
      --k3s      "${K3S_CONFIG}" \
      --cluster  "${CLUSTER_CONFIG}" \
      --seed-dir "${SEED_DIR}"
  fi

  # (b) start-bird / start-kernel: topology-agnostic helpers.
  custom_script=""
  case "${ACTION}" in
    start-bird)   custom_script="seed_k8s_start_bird0130.py" ;;
    start-kernel) custom_script="seed_k8s_start_bird_kernel.py" ;;
  esac
  if [ -n "${custom_script}" ]; then
    custom_validation="${SEED_DIR}/output/profile_runs/${PROFILE}/latest/validation"
    mkdir -p "${custom_validation}"
    # Upstream profile_runner exports KUBECONFIG itself (L321), but we're
    # bypassing it — export here so the python helper's kubectl calls find
    # the cluster. The path is the one seed_k3s_setup.sh mirrors to for the
    # upstream runner's hardcoded expectation.
    export KUBECONFIG="${SEED_DIR}/output/kubeconfigs/${SEED_K3S_CLUSTER_NAME:-seedemu-k3s}.yaml"
    log "custom profile bypass: invoke ${custom_script} directly (skip upstream PROFILE_ID gate)"
    exec python3 "${SEED_DIR}/scripts/${custom_script}" "${SEED_NAMESPACE:-seedemu-custom}" "${custom_validation}"
  fi
fi

# 5) Hand off to the upstream profile runner
#
# macOS quirk: SEED upstream profile_runner.sh uses bash 4+ \${VAR@Q}
# syntax. Mac /bin/bash is 3.2 (GPL-v2 locked). Explicitly invoke
# /opt/homebrew/bin/bash so the upstream script gets a 4+ shell.
# (The Python interpreter selection is handled by scripts/bin/python3
# shim which scripts/bin is prepended to PATH at line 42.)
if [ "$(uname)" = "Darwin" ]; then
  BASH_BIN="/opt/homebrew/bin/bash"
  [ -x "$BASH_BIN" ] || BASH_BIN="bash"
else
  BASH_BIN="bash"
fi
exec "${BASH_BIN}" "${PROFILE_RUNNER}" "${PROFILE}" "${ACTION}"
