provider: virtualbox
box: generic/ubuntu2204
box_arm64: gyptazy/ubuntu22.04-arm64
network:
  type: private_network
nested_virt: false
workers: 2
master:
  cpus: 2
  memory: 4096
worker:
  cpus: 2
  memory: 2048
