cluster_name: seedemu-k3s
reference_cluster: true
runtime: k3s
max_validated_topology_size: 214
k3s:
  cluster_cidr: 10.42.0.0/16
  service_cidr: 10.43.0.0/16
  node_cidr_mask_size_ipv4: 24
  max_pods: 110
ssh:
  user: vagrant
  key_path_env: SEED_K3S_SSH_KEY
  default_key_path: /home/r1al1ce/.vagrant_keys/vagrant.key.rsa
registry:
  host: 192.168.77.10
  port: 5000
cni:
  default_master_interface: eth1
nodes:
- name: master
  role: master
  management_ip: 192.168.77.10
  runtime: k3s
  labels:
    kubernetes.io/hostname: master
- name: worker1
  role: worker
  management_ip: 192.168.77.11
  runtime: k3s
  labels:
    kubernetes.io/hostname: worker1
- name: worker2
  role: worker
  management_ip: 192.168.77.12
  runtime: k3s
  labels:
    kubernetes.io/hostname: worker2
